### ISSUE TITLE
Default window height

### ISSUE THREAD

**Issue by liloman** [fboender/bexec#2]
Hi, 

It'll be really cool if you could set the default window height/width. It's really annoying for me keep downsizing the output window manually each time. 

Something like :10sp would be nice.

Cheers and thanks. :)

**Comment by fboender** [comment]
Hi!

Thanks for the feature request. I'm going to look into this soon. It seems like a nice feature to have.

**Comment by liloman** [comment]
Niiice. :)

Another issue will be to close automatically the output buffer on exit and don't have to close it every time by yourself. Something like a hook I suppose it must be possible to do but I have no clue right now. :)

Thanks for the plugin I've been using it for years with just these two little nuisances.

**Comment by fboender** [comment]
Hi!

I've just released v0.10 of Bexec, which includes a new setting: `bexec_splitsize`. Setting it to a number will automatically open the output buffer at that size.

I'm going to have to think about the automatic output buffer closing thing. I'm not sure what the best approach would be yet.

Thanks for the feature request!

**Comment by liloman** [comment]
Niiice. :)

The automatic close will be great too. :)

**Comment by fboender** [comment]
I've created a new issue (#3) for the window closing
