### ISSUE TITLE
Remove default mapping

### ISSUE THREAD

**Issue by ciases** [fboender/bexec#8]
Hello there!
I have a problem with default mapping `,bx` and `,bl`.
I use `CtrlP` plugin and map `<leader>b` (`,b` in my case) to show buffers. Now when I hit `,b` vim waits for a while (it waits for another sign to know exactly is it a `,b` or `,bx` command). So, for now `CtrlP` starts show buffer very slowly.
It would be nice to remove default `,bx`, `,bl` mappings.

**Comment by fboender** [comment]
You can remove the default mappings for bexec by adding the following to your .vimrc:

    autocmd VimEnter * unmap <leader>bx
    autocmd VimEnter * unmap <leader>bc
    autocmd VimEnter * unmap <leader>bl

You can then optionally remap them to a different binding:

    nmap <silent> <unique> <Leader>xx :call bexec#Normal()<CR>
    vmap <silent> <unique> <Leader>xx :call bexec#Visual()<CR>
    nmap <silent> <unique> <Leader>xc :call bexec#Live()<CR>
    nmap <silent> <unique> <Leader>xl :call bexec#CloseOut()<CR>

Would that fix things for you?

**Comment by ciases** [comment]
Oh, it works great now! Thank you!
